# Setup frontend with Cognito configuration

Write-Host "🔧 Setting up frontend configuration..." -ForegroundColor Cyan
Write-Host ""

# Get stack outputs
Write-Host "Getting Cognito details from AWS..." -ForegroundColor Yellow

$stackName = "expense-tracker-dev"
$outputs = @{}

try {
    $stackInfo = aws cloudformation describe-stacks --stack-name $stackName 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        $stack = $stackInfo | ConvertFrom-Json
        
        foreach ($output in $stack.Stacks[0].Outputs) {
            $outputs[$output.OutputKey] = $output.OutputValue
        }
        
        $userPoolId = $outputs["UserPoolId"]
        $clientId = $outputs["UserPoolClientId"]
        $apiEndpoint = $outputs["ApiEndpoint"]
        
        if ($userPoolId -and $clientId) {
            Write-Host "✓ Found Cognito configuration!" -ForegroundColor Green
            Write-Host ""
            Write-Host "User Pool ID: $userPoolId" -ForegroundColor White
            Write-Host "Client ID: $clientId" -ForegroundColor White
            Write-Host "API Endpoint: $apiEndpoint" -ForegroundColor White
            Write-Host ""
            
            # Update config file
            $configPath = "frontend\src\config-auth.js"
            $configContent = @"
// Configuration with authentication
// Auto-generated by setup-frontend.ps1

const config = {
  cognito: {
    userPoolId: '$userPoolId',
    clientId: '$clientId',
    region: 'us-east-1'
  },
  api: {
    endpoint: '$apiEndpoint',
    useAuth: true
  }
};

export default config;
"@
            
            Set-Content -Path $configPath -Value $configContent
            Write-Host "✓ Updated $configPath" -ForegroundColor Green
            Write-Host ""
            Write-Host "🎉 Setup complete! Now run:" -ForegroundColor Cyan
            Write-Host "   cd frontend" -ForegroundColor White
            Write-Host "   npm start" -ForegroundColor White
            Write-Host ""
        } else {
            Write-Host "✗ Could not find Cognito outputs" -ForegroundColor Red
        }
    } else {
        Write-Host "✗ Stack not found. Make sure backend is deployed:" -ForegroundColor Red
        Write-Host "   serverless deploy" -ForegroundColor White
    }
} catch {
    Write-Host "✗ Error getting stack info: $_" -ForegroundColor Red
    Write-Host ""
    Write-Host "Manual setup required:" -ForegroundColor Yellow
    Write-Host "1. Go to AWS Console → CloudFormation" -ForegroundColor White
    Write-Host "2. Find stack: expense-tracker-dev" -ForegroundColor White
    Write-Host "3. Click Outputs tab" -ForegroundColor White
    Write-Host "4. Copy UserPoolId and UserPoolClientId" -ForegroundColor White
    Write-Host "5. Update frontend/src/config-auth.js" -ForegroundColor White
}
